### ISSUE TITLE
项目不完整？

### ISSUE THREAD

**Issue by leonmax120** [skyvow/m-mall-admin#1]
您好，

大概在Linux上面装了一下您开发的这个， 有报错。 也看了您demo网站的成品。看了看您的代码里面 发现没有发现有前端的代码 求大神您指教一下 是不是缺什么东西

**Comment by skyvow** [comment]
前台：[m-mall](https://github.com/skyvow/m-mall)

**Comment by leonmax120** [comment]
大神 你这个后台的东西是不是需要编译才能变成这个： https://www.skyvow.cn/index/home

**Comment by skyvow** [comment]
后台页面源码位于public/src/，需要编译生成build/

**Comment by leonmax120** [comment]
大神不好意思再问一下你的 npm 和 node.js 是什么version的啊？ 我这个version是不是不是你开发时候用的version
![image](https://cloud.githubusercontent.com/assets/1075937/22048690/ba2adfc0-dd82-11e6-8cd9-503e915b92f9.png)

**Comment by leonmax120** [comment]
大神再问一下你的那个是什么version的npm 和node.js。 貌似我的version不太对啊

![image](https://cloud.githubusercontent.com/assets/1075937/22048728/074f20f4-dd83-11e6-9b88-f10be5f5dd7a.png)
