### ISSUE TITLE
老哥，项目要用什么软件打开？

### ISSUE THREAD

**Issue by SummerTK** [skyvow/m-mall-admin#12]

**Comment by xdlStrive** [comment]
基于node.js的后台啊，前台用微信官方提供的微信web开发者工具，后台就用node.js、mongodb、redis等。用npm配置环境就OK了...

**Comment by SummerTK** [comment]
没弄过这些，我学习都是vs和dw来开发，想了解一下

**Comment by sherwinzz** [comment]
@xdlStrive 可以详细说明一下么 我qq2991342957

**Comment by xdlStrive** [comment]
前面已经说得很清楚了啊，如果你要打开这个小程序的前台就用微信官方的Web开发者工具，如果要打开这个后台的话就下载安装node.js、mongodb、和redis，也可以安装完node.js后就用npm安装后面两个。
环境搭建好之后就可以启动项目了
1、C\redis下打开redis-server.exe

2、C盘打开mongoBD的bin下的mongod.exe

3、执行 mongod --dbpath C:\date 命令

4、E盘wechat下执行 npm start命令

5、浏览器输入地址http://localhost:3000/user/login即可打开后台
windows环境就用cmd命令控制台打开就好，linux系统我不是很清楚...

**Comment by xdlStrive** [comment]
上面一二步对应的是redis和mongodb的安装路径，第三步对应的是设置的mongodb的data文件夹的路径，第四步是这个项目的路径

**Comment by busterace** [comment]
哥，按照这个我跑起来了，如果我想debug是怎么搞啊

**Comment by MXHanner** [comment]
为什么在登陆界面点立即登陆没有反应呢
