### ISSUE TITLE
入口页面url是什么？

### ISSUE THREAD

**Issue by woderia** [skyvow/m-mall-admin#2]
http://localhost:3000/返回404 没有报错信息

**Comment by woderia** [comment]
![m 8475 szb7t a 0huctlj](https://cloud.githubusercontent.com/assets/1846796/21972508/16c56ac8-dbf5-11e6-9091-34dce6ba2969.png)
登录的时候报错

**Comment by xdlStrive** [comment]
后台登录页面的URL是：http://localhost:3000/user/login
