### ISSUE TITLE
public目录下，编译没有生成build文件

### ISSUE THREAD

**Issue by zhyq** [skyvow/m-mall-admin#22]
作者您好，首先感谢你无私奉献精神，分享代码快乐。
我在npm install后
npm run build 运行结束后没有生成 build目录
我看您回复其他问题时，说要在public下面编译出build文件，确实，webpack.config.js中确定党env为production时dist为 build目录，求解决

**Comment by zhyq** [comment]
是不是 output的 dist 要叫上 前面的路径  __dirname?

**Comment by skyvow** [comment]
@zhyq cd public、npm install、npm run build

**Comment by zhyq** [comment]
您好，是这么做的，并且npm run build没有报错，运行完之后，没有建立build目录
