### ISSUE TITLE
这个项目后台怎么启动？

### ISSUE THREAD

**Issue by shuiyunwudi** [skyvow/m-mall-admin#23]
有大侠可以详细讲一讲么？这个后台用到了mongodb、redis啥的，整个是如何启动的？对这些没什么了解。执行npm start 命令报错了，说babel-node不是内部命令。

**Comment by skyvow** [comment]
@shuiyunwudi 看看[README](https://github.com/skyvow/m-mall-admin/blob/master/README.md)

**Comment by shuiyunwudi** [comment]
是进入到项目目录下，执行npm start命令吧？然而我执行过后报下面的错：
![qq 2](https://user-images.githubusercontent.com/31852238/30362085-c98a555c-988c-11e7-90b6-5b9bc47419a1.png)

**Comment by skyvow** [comment]
@shuiyunwudi 提示模块没找到，有没有执行 npm install 安装依赖包？

**Comment by shuiyunwudi** [comment]
执行了，它的上一句就是执行的npm install.是不是跟node.js的版本有关，我用的是4.4.3@skyvow
