### ISSUE TITLE
访问不了api

### ISSUE THREAD

**Issue by ping-chen** [skyvow/m-mall-admin#28]
后台已经跑起来，后台管理也能登录。

但是微信端获取api的接口，全部是401

build目录已经本地生成，上传服务器（服务生成build，就卡死自动取消，这是个问题）

请问，我还差什么？

后台说：No authorization token was found
是token没有设置吗？
弄了一天，没成功，还请指教下！

**Comment by skyvow** [comment]
@ping-chen `app.use(/^((?!sign\/up|sign\/in|captcha).)+$/, [
	jwt({ secret: config.secret}), 
	auth.verifyToken.bind(auth)
])`

接口（除 sign/up、sign/in、captcha 之外）是都是非开放性的，基于 JSON Web Tokens 后台身份验证。登录成功后返回一个有效 token，之后每次请求都会放在请求头 headers 里面 Authorization: token，认证成功返回 200， 失败返回 401。

**Comment by ping-chen** [comment]
非常感谢，可以了。
这里是小程序的token处理？根据appid，secret作为处理的吗？

还有件事，整套程序，要用到 npm -g babel babel-cli webpack express 
好像就这几个吧，我都记不清了，今天在新云服务器部署，你的readme没有写的太清楚
调了一个下午。
最要命的是public 缺少.babelrc 导致npm run build 报错中止


以上是centos7服务器上部署

最后，感谢作者的开源。让我可以好好学习！
