### ISSUE TITLE
为什么数据会丢失？

### ISSUE THREAD

**Issue by ping-chen** [skyvow/m-mall-admin#31]
我有腾讯云部署的，放那里，一段时间，数据库的数据就全没了！

**Comment by yuangang123** [comment]
不知道为何部署后台之后
微信小程序前端显示不出来图片

**Comment by skyvow** [comment]
@ping-chen 可能被攻击了吧

**Comment by skyvow** [comment]
@yuangang123 图片路径对不对？

**Comment by ping-chen** [comment]
@skyvow 不太像，我另一个数据库是好的。

**Comment by kingdee88** [comment]
@yuangang123 看下日志不就知道了，估计数据库没设置密码，被攻击了
