### ISSUE TITLE
页面一直在转圈圈

### ISSUE THREAD

**Issue by Attache** [skyvow/m-mall-admin#34]
在npm run build后，中间出现

ERROR in multi vendor
Module not found: Error: Cannot resolve module 'angular-i18n/angular-locale_ZH-CN.js' in /home/m-mall-admin/public
 @ multi vendor

另外，我的centos没有安装中文。

**Comment by Attache** [comment]
修改 public/node_modules/angluar-i18n/下的angular-locale_zh-cn.js为angular-locale_ZH-CN.js即可编译通过。

**Comment by baitongda** [comment]
测试完全可以用
