### ISSUE TITLE
大神，怎么添加一个取消订单的功能啊？

### ISSUE THREAD

**Issue by xdlStrive** [skyvow/m-mall-admin#7]
我自己弄出了一个直接删除掉订单的功能，但订单分类里有“已取消”这个分类，所以我想请教一下大神，应该怎么才能更改订单的状态？

**Comment by skyvow** [comment]
设计一个字段，然后每次操作订单表，字段变化来存储，字段可以标识订单的状态（已提交、已取消、已支付等等）。

**Comment by xdlStrive** [comment]
大神，我换了台电脑配置后台，环境都配置好了后打开后台登录页面时一直显示loading是怎么回事啊？
